from pathlib import Path

ROOT_DIR = Path(__file__).parent
DATA_DIR = ROOT_DIR / "data"
ENTERPRISE_DOCS_DIR = DATA_DIR / "enterprise_docs"
COMPLEX_DOCS_DIR = DATA_DIR / "complex_docs"

MAX_CHUNK_TOKENS = 512
APPROX_CHARS_PER_TOKEN = 4
MAX_CHUNK_CHARS = MAX_CHUNK_TOKENS * APPROX_CHARS_PER_TOKEN
CHUNK_OVERLAP_RATIO = 0.15
OVERLAP_CHARS = int(MAX_CHUNK_CHARS * CHUNK_OVERLAP_RATIO)

SEMANTIC_SIM_THRESHOLD = 0.75

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

QDRANT_COLLECTION = "chunking_compare"
